.TH FID 1
.SH NAME
fid \- query id database for specific files
.SH SYNOPSIS
.B fid
.RB [ \-f \^file]
file1 [ file2 ]
.SH DESCRIPTION
.I Fid
is a query tool for the id database. If you specify a single file
name as an argument, it prints a list of all the identifiers that
occur in that file.
.PP
When you give it two file names it takes the intersection. It prints
only the list of identifiers that occur in both files.
.PP
The following options are recognized:
.TP 10
.BR \-f file\^
Use
.I file\^
as the database instead of the default
.BR ID .
.SH SEE ALSO
mkid(1),
lid(1).
