#!/bin/sh
# This would provoke an infloop with source from 4.2+ (cvs as of 2007-01-19).

# Copyright (C) 2007, 2009-2010 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  mkid --version
  aid --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1
echo 'boo[! bar[]' > f.el || framework_failure=1

# FIXME: The expected output should probably be these two lines:
#   bar
#   boo[]
# but the code to handle that (now-disabled) did a double-ungetc.
cat <<EOF > exp || framework_failure=1  # expect no output
bar
boo
EOF

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

lang_map="$abs_top_srcdir/libidu/id-lang.map"
mkid -m "$lang_map" f.el > out || fail=1
aid -R none b >> out || fail=1

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
